message: Hello, this is Yexingyu's config!
author: yexingyu

---

spring:
  profiles:
    active: dev  # 默认激活dev环境
---
spring:
  profiles: dev
  application:
    name: mldnconfig-test-dev
---
spring:
  profiles: product
  application:
    name: mldnconfig-test-product