# application.yml in Git repo

message: Hello, this is Yexingyu's config!
author: yexingyu

---

spring:
  profiles:
    active: product  # 生产环境默认激活product

---

spring:
  profiles: dev
  application:
    name: mldncloud-config-client
  datasource:
    url: jdbc:mariadb://localhost:3306/dept8001
    username: root
    password: 123456
  jpa:
    show-sql: true
  server:
    port: 8101

---

spring:
  profiles: product
  application:
    name: mldncloud-config-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://localhost:3306/dept8001
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "{cipher}AQBNFN/+uOGCdov4QGzYvX1x4m9S0/vXbcPaGFlFPCiLR+XtUJTj78XEbyPjz1miV81vEOYUIjfFGqGTFI00NUVRKSr7PWPTSRecF84UvTqwyb0qm3O9pW9r8Aqq9yYZaVVrNo1oTe8WRtWTubeQTS1z8fyXs2sbc9LAuOrF0k8SNOIjtmeFoKi7s+1m2wY/DA0EhaBSeKxTt4v0fvArpuzX82awmTARDDuOGADlw55JlcTEQE5CoxU1LYgGOMHnNPUrbju/YJlg0A6pEgHBkwVHsn7c0sNe48+fB0A3t/WSaSdVlFN4BtQmIGLiWWYWp4UGEBxioW62jLU7bzfMzNQZcqZkBjfjf7+4W4828Mi35kmoZxGaU9d8eZzwp4D8mdY="
    dbcp2:
      initial-size: 1
      min-idle: 1
      max-total: 1
      max-wait-millis: 200
      test-while-idle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
  jpa:
    show-sql: true
  server:
    port: 8102
